name: cosc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  get: ^4.6.5

  # Configuration
  flutter_config: ^2.0.0 # For Env File
  flutter_svg: ^1.1.6

  # Get configuration from yarml file
  yaml: 3.1.1

  # dart에서 == 사용해서 객체 비교
  equatable: ^2.0.5

  # 카드 스와이퍼
  flutter_swiper: 1.1.6

  # 달력 라이브러리 (2개중 하나 사용해보고 좋은거 선택)
  table_calendar: 3.0.8
  syncfusion_flutter_calendar: ^20.3.61

  # flutter font
  google_fonts: ^3.0.1

  # UI
  percent_indicator: ^4.2.2
  lottie: ^1.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/social/
    - assets/image/
    - assets/lottie/
    - pubspec.yaml

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
